### ISSUE TITLE
Milestone 0 Demo

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#658]
### Detailed Description

Demo should show off all functionality which is expected to work and highlight the simplicity of installation and usage.  Demo should be documented.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by berndtj** [comment]
https://VMware.zoom.us/recording/share/EKnPwFufy2qhhH5LfydGh1ea7pC_tsPFqvFSV-zHMU-wIumekTziMw
